divvi-xyz/hooks

- src/apps/moola/debtTokens.ts
- src/apps/moola/plugin.e2e.ts
- src/apps/moola/plugin.test.ts
- src/apps/moola/plugin.ts
Adding a plugin for Moola: debt tokens are mapped to a position with the negative `usdPrice` of the base token.
> feat: Moola plugin

- docs/position-pricing-hooks.md
- scripts/getPositions.ts
- src/runtime/getPositions.ts
- src/types/positions.ts
Follow up from https://github.com/valora-inc/hooks/pull/111
> docs: rename more references to plugins

- src/apps/uniswap/abis/user-positions.ts
- src/apps/uniswap/positions.e2e.ts
- src/apps/uniswap/positions.ts
Added Uniswap position hook. It doesn't fetch the claimable fees data. Could be added as a shortcut to claim them next.
> feat: Add Uniswap positions hook

- src/runtime/getPositions.ts
- test/server.ts
See https://github.com/valora-inc/valora-rest-api/pull/645
> chore: use renamed tokens info endpoint

- src/apps/aave/abis/incentives-controller-v3.ts
- src/apps/aave/abis/ui-incentive-data-provider.ts
- src/apps/aave/constants.ts
- src/apps/aave/positions.ts
- src/apps/aave/shortcuts.e2e.ts
- src/apps/aave/shortcuts.ts
| Positions | Claim |
|-|-|
| ![IMG_6675](https://github.com/user-attachments/assets/8c249465-6d32-49f2-8d9b-a11217de09e4) | ![IMG_6676](https://github.com/user-attachments/assets/5c5c74a2-0e38-46e2-b984-d5f5da6ddf9a) |
Note: As you can see, multichain claims are currently broken in Valora. Only 1 should be displayed and it should show the claimed token. I'll fix this in the wallet.
> feat(aave): show rewards and allow claiming them

- src/types/positions.ts
Added TVL as an optional param in dataProps, this is needed for the new multi-pool UI
> feat(earn): Add TVL to dataProps

- src/apps/aave/constants.ts
- src/apps/aave/positions.ts
- src/apps/allbridge/constants.ts
- src/apps/allbridge/positions.ts
- src/types/positions.ts
Allbridge URL narrows it down to network (can't get more specific) ([example](https://core.allbridge.io/pools?chain=CEL)), Aave also narrows down to network.
**Got contractCreatedAt time from below:**
TX to create Allbridge pool: https://celoscan.io/tx/0x6687ad44ab293981f299c0ed6638d8f575835d7bdbe29a426abeede7ee4ed7d0
TX to create Aave pool token (mainnet): https://arbiscan.io/tx/0x904364beeab39ba08a36254891516f94de49af3e0c7272c516a90a678a2a8cc0 
TX to create Aave pool token (sepolia): https://sepolia.arbiscan.io/tx/0x3cf0d9895d1e48aec4b48f74ff7c814b09bdda433dba29aa4440381e75eea500
**Testing:**
```
yarn getPositions --networkId celo-mainnet --apps allbridge --address 0x644b896b0c45717215c0f10501b20fafd9bceb24
```
```
"dataProps": {
"manageUrl": "https://core.allbridge.io/pools?chain=CEL", …
```
> feat(earn): Add manageUrl and contractCreatedAt to Aave and Allbridge

- src/api/index.ts
```
yarn deploy:staging:http hooks-api
```
```
curl https://api.alfajores.valora.xyz/hooks-api/getEarnPositions?networkIds=arbitrum-sepolia
```
> fix(earn): Get translations to work with api

- src/apps/aave/constants.ts
- src/apps/aave/positions.ts
- src/apps/allbridge/constants.ts
- src/apps/allbridge/positions.ts
- src/types/positions.ts
> feat: add terms url to earn data props

- src/apps/aave/shortcuts.ts
- src/runtime/simulateTransactions.test.ts
- src/runtime/simulateTransactions.ts
This new approach handles cases where networks aren't supported and when simulation fails for some reason.
> chore: tweak simulation ergonomics

- src/api/production.yaml
- src/api/staging.yaml
Time has come to turn these boys on! https://github.com/valora-inc/wallet/pull/5856#discussion_r1737013974
> feat(shortcuts): Enable shortcuts for aave and allbridge

- src/apps/aave/positions.ts
- src/apps/allbridge/positions.ts
- src/runtime/getPositionId.test.ts
- src/runtime/getPositionId.ts
- src/runtime/getPositions.ts
- src/types/positions.ts
This way clients can identify what reward is associated with an earn position
> feat: add reward position ids to earn data props

- src/apps/aave/positions.ts
From bugapalooza issue https://valora-app.slack.com/archives/C04B61SJ6DS/p1725638194169029
> fix(aave): add positionAddress to shortcutTriggerArgs

- README.md
Be less Valora-specific because it's used across mobilestack applications now.
> docs(README.md): small tweaks

- src/apps/allbridge/positions.ts
while we figure out options for getting this working
> feat(allbridge): turn off swap-deposit

- src/apps/allbridge/api.ts
- src/apps/beefy/api.ts
- src/apps/curve/positions.ts
- src/apps/halofi/haloFiApi.ts
- src/apps/hedgey/nfts.ts
- src/apps/ubeswap/positions.ts
- src/runtime/getPositions.test.ts
- src/runtime/getPositions.ts
- src/runtime/simulateTransactions.test.ts
- src/runtime/simulateTransactions.ts
- src/utils/got.ts
- src/utils/prepareSwapTransactions.test.ts
- src/utils/prepareSwapTransactions.ts
by default got has no timeouts, adding 10s timeouts to all requests
> fix(got): add timeouts to all requests

- src/utils/prepareSwapTransactions.ts
Pass `enableSwapFee` down to `getSwapQuote`.
Part of ACT-1379
> chore(earn): pass enableSwapFee to getSwapQuote

- src/apps/aave/shortcuts.ts
- src/apps/allbridge/shortcuts.ts
Pass enableSwapFee correctly: [related thread](https://github.com/valora-inc/hooks/pull/561#discussion_r1769461313).
> fix(fees): pass enableSwapFee to prepareSwapTransactions

- src/apps/aave/shortcuts.ts
- src/apps/allbridge/shortcuts.ts
- src/types/shortcuts.ts
- src/utils/prepareSwapTransactions.ts
Renames `enableSwapFee` to `enableAppFee`: [Relevant Comment](https://github.com/valora-inc/hooks/pull/570#discussion_r1775250180).
> style: rename enableSwapFee to enableAppFee

- package.json
This is required for concurrency > 1 https://github.com/valora-inc/hooks/actions/runs/11038172984/job/30660925070
> ci: set cpu to 1

- src/apps/beefy/api.ts
- src/apps/beefy/positions.ts
Part 1 of ACT-1369, will add shortcut info in a follow up
> feat(beefy): add earn data props

- src/apps/beefy/positions.e2e.ts
- src/apps/beefy/positions.ts
So this can be used to display earn positions. Actually returning beefy earn positions will be done in ACT-1367
> feat(beefy): return positions with 0 balance when address is not set

- src/apps/beefy/positions.ts
- src/runtime/getPositions.ts
- src/types/positions.ts
Saves a contract call to get decimals
> refactor(positions): use context for shortcut trigger args

- scripts/getPositions.ts
- src/api/index.ts
- src/apps/beefy/positions.e2e.ts
- src/apps/compound/positions.e2e.ts
- src/apps/ubeswap/positions.e2e.ts
- src/runtime/getPositions.e2e.ts
- src/runtime/getPositions.test.ts
- src/runtime/getPositions.ts
Currently makes one call per network, this should cut the load 5x
> refactor(positions): make one call to getTokensInfo per request

- package.json
- src/apps/aave/constants.ts
- yarn.lock
> revert(aave): updating aave addresses to use their npm package instead of hardcoded

- src/api/production.yaml
- src/api/staging.yaml
https://twitter.com/halofi_me/status/1839282033014534617
> chore: disable halofi (the API is down)

- src/apps/beefy/shortcuts.ts
Noticed a few failures due to running out of gas
> fix(beefy): adjust deposit gas padding

- src/apps/beefy/api.ts
- src/apps/beefy/positions.ts
There's been an uptick in [errors](https://cloudlogging.app.goo.gl/NqLMhFrQ4Kb5ncHB6) since #620 merged.
> fix(beefy): handle undefined apyBreakdown

- src/api/index.ts
- src/api/production.yaml
- src/api/staging.yaml
- src/runtime/getPositions.ts
I won't merge till monday
https://linear.app/valora/issue/ACT-1422/blockchain-api-move-tokensinfo-endpoint-to-a-cloud-fn
> chore(api): Use new tokensInfo endpoint with networkIds query param

- docs/index.md
- docs/types/shortcut.md
> chore: fix typos

- src/api/index.ts
- src/api/production.yaml
- src/api/staging.yaml
Related to RET-1258
Silas added this pool to the testers group in Statsig, it won't be enabled for all users yet.
> feat(somm): enable Somm Real Yield WETH on optimism

- src/apps/beefy/positions.test.ts
- src/apps/beefy/positions.ts
https://valora-app.slack.com/archives/C04B61SJ6DS/p1735833604857669
> fix(beefy): format pools pricePerShare correctly

- src/utils/prepareSwapTransactions.test.ts
- src/utils/prepareSwapTransactions.ts
Related to change done in https://github.com/valora-inc/valora-rest-api/pull/1226
> fix(swap-deposit): use gas field directly

- package.json
- src/apps/allbridge/api.ts
- src/config/index.ts
Add support for our Allbridge header to prevent rate-limiting; Users without this header / api-key should not be impacted.
> feat: optionally use allbridge header if provided

- package.json
- src/api/index.test.ts
- src/api/index.ts
- yarn.lock
As per the title.
Relates to [ENG-255](https://linear.app/valora/issue/ENG-255/hooks-functions-and-transactions-poc)
> feat: add CORS management

- package.json
- scripts/getPositions.ts
- src/apps/aave/abis/ui-incentive-data-provider.ts
- src/apps/aave/abis/ui-pool-data-provider-v3.ts
- src/apps/aave/constants.ts
- src/apps/aave/getAaveTokensWithIncentives.ts
- src/apps/aave/positions.ts
- yarn.lock
Aave now uses new contracts for  UI_POOL_DATA_PROVIDER and UI_INCENTIVE_DATA_PROVIDER. All the chains needed to be updated to support celo, which was only deployed using the new contracts.
```
$ ts-node ./scripts/getPositions.ts --networkId celo-mainnet  --apps aave
┌─────────┬────────┬─────────────┬──────────────────────────────────────────────┬────────────────┬───────────────────────────────────────────────┬──────────┬─────────┬────────────┬─────────────────────────────┬───────────────────────────────────────────┐
│ (index) │ appId  │ type        │ address                                      │ network        │ title                                         │ priceUsd │ balance │ balanceUsd │ breakdown                   │ availableShortcutIds                      │ …
```
> fix(aave): Support new celo pools

- package.json
- src/apps/aave/abis/ui-incentive-data-provider.ts
- src/apps/aave/abis/ui-pool-data-provider-v3.ts
- src/apps/aave/constants.ts
- src/apps/aave/getAaveTokensWithIncentives.ts
- src/apps/aave/positions.ts
- yarn.lock
Reverts divvi-xyz/hooks#814
Caused issues with balances displaying, requires more investigation: https://valora-app.slack.com/archives/C02N3AR2P2S/p1744816193851329
> revert(aave): revert supporting new aave pools

- package.json
- src/apps/aave/abis/ui-incentive-data-provider.ts
- src/apps/aave/abis/ui-pool-data-provider-v3.ts
- src/apps/aave/constants.ts
- src/apps/aave/getAaveTokensWithIncentives.ts
- src/apps/aave/positions.ts
- yarn.lock
Now returns balances correctly:
```
ts-node ./scripts/getPositions.ts --networkId arbitrum-one  --apps aave --address 0x957d3274a02742ff5913a19246b17a21572d3772
┌─────────┬────────┬─────────────┬──────────────────────────────────────────────┬────────────────┬────────────────────────────────┬──────────┬─────────┬────────────┬─────────────────────────────┬───────────────────────────────────────────┐
│ (index) │ appId  │ type        │ address                                      │ network        │ title                          │ priceUsd │ balance │ balanceUsd │ breakdown                   │ availableShortcutIds                      │
├─────────┼────────┼─────────────┼──────────────────────────────────────────────┼────────────────┼────────────────────────────────┼──────────┼─────────┼─────── …
```
> fix(aave): Add new celo aave pools correctly
