src/apps/halofi/plugin.ts, src/apps/locked-celo/plugin.ts, src/apps/ubeswap/plugin.ts
For now we'll use the dapp logo as the position image. This PR adds the images from our dapps list for halo-fi and ubeswap, and the Celo assets image for locked celo.
Fixes RET-734
=> chore: add image urls for existing positions

scripts/triggerShortcut.e2e.ts, scripts/triggerShortcut.ts, src/apps/ubeswap/shortcuts.ts, src/shortcuts.ts
This implements the `onTrigger` method of the `claim-reward` shortcut for Ubeswap.
The `triggerShortcut` command line tool was updated to be able to send the resulting transaction.
Fixes RET-732
Here's our first successful shortcut call:
```
❯ yarn triggerShortcut --network celo --address 0x2b8441ef13333ffa955c9ea5ab5b3692da95260d --app ubeswap --shortcut claim-reward --positionAddress 0xda7f463c27ec862cfbf2369f3f74c364d050d93f --mnemonic "[XXX]"
yarn run v1.22.19
$ ts-node ./scripts/triggerShortcut.ts --network celo --address 0x2b8441ef13333ffa955c9ea5ab5b3692da95260d --app ubeswap --shortcut claim-reward --positionAddress 0xda7f463c27ec862cfbf2369f3f74c364d050d93f --mnemonic [XXX]
Triggering shortcut 'claim-reward' for app 'ubeswap' {
network: 'celo',
address: …
```
=> feat: implement ubeswap claim reward shortcut + update cli tool to test

docs/position-pricing-hooks.md, scripts/getPositions.ts, src/apps/halofi/positions.e2e.ts, src/apps/halofi/positions.ts, src/apps/locked-celo/positions.e2e.ts, src/apps/locked-celo/positions.test.ts, src/apps/locked-celo/positions.ts, src/apps/moola/positions.e2e.ts, src/apps/moola/positions.test.ts, src/apps/moola/positions.ts, src/apps/ubeswap/positions.e2e.ts, src/apps/ubeswap/positions.ts, src/getHooks.ts, src/getPositions.ts, src/positions.ts
This moves positions plugins to the new "hooks" terminology.
Following the addition of shortcuts.
=> refactor!: rename plugin -> positions

src/apps/halofi/haloFiContract.ts, src/apps/halofi/positions.ts
Bug fix and optimization for the halofi hook:
- Getting token decimals from "resolvedTokens" instead of querying on chain data.
- Bug fix: Filter Halofi games where the user has withdrawn
=> fix: Halofi hook should filter withdrawn games

docs/position-pricing-hooks.md, src/apps/ubeswap/positions.ts, src/runtime/getPositions.ts
Moved the noisy `console.log` in the runtime to `logger.debug`
=> chore: reduce excessive logs

src/apps/ubeswap/positions.ts
Following the delisting of Ubeswap in https://github.com/valora-inc/dapp-list/pull/510
The related positions image was broken.
**before/after**
=> fix(ubeswap): missing image since it was removed from dapp-list

src/apps/uniswap/positions.ts
Once the liquidity is withdrawn, we shouldn't display a position.
See Slack [thread](https://valora-app.slack.com/archives/C04B61SJ6DS/p1695662883555879).
The thread is about something else, but I noticed this other bug in the screenshot.
=> fix(uniswap): hide positions with no liquidity

src/apps/gooddollar/shortcuts.ts, src/apps/ubeswap/shortcuts.ts, src/types/shortcuts.ts
The runtime already resolves the value .getShortcutDefinitions returns.
=> refactor(getShortcutDefinitions): define to return a promise

src/runtime/client.ts
strangely, the build fails while deploying, but not locally, without this return type. see [here](https://console.cloud.google.com/cloud-build/builds;region=us-central1/08bd8607-3f69-4b7d-aae6-69116fa6e414;step=2?project=celo-mobile-alfajores)
tested by deploying to staging
cc https://linear.app/valora/issue/RET-941/%5Bhooks%5D-multichain-support which I am doing on a contract basis
=> fix: explicit return type for getClient

src/api/index.test.ts, src/api/index.ts
BREAKING CHANGE: instead of singular "networkId", takes array "networkIds" as query parameter for endpoints to get positions and shortcuts. The "networkId" query param was added recently (by me) and not used by any wallet versions, so this should be ok.
In my last hooks PR, I assumed we would want to keep the api more or less intact, just substituting "networkId" for "network" since it expected different values. However, when I went to implement the wallet changes, I noticed that we'd need to make a separate request to the hooks endpoints for every network we want to support, which doesn't scale well. Taking multiple network ID's as a query parameter seems like the better approach. 
tested manually with local wallet build, verified that Celo and Eth positions can be displayed together.
=> refactor(multichain)!: accept multiple network ids for get positions and get shortcuts

src/runtime/getPositions.test.ts, src/runtime/getPositions.ts, src/types/positions.ts
Related to https://github.com/valora-inc/hooks/pull/396 and discussed with @gnardini ([thread](https://valora-app.slack.com/archives/C04NFRMSZQX/p1718275117206789))
This should make it easier to implement Beefy which relies on a wide variety of underlying tokens for which we don't yet have apps that could decompose them.
=> feat: add fallbackPriceUsd as escape hatch

scripts/getPositions.ts, src/apps/curve/positions.ts, src/apps/gooddollar/positions.ts, src/apps/halofi/positions.ts, src/apps/hedgey/positions.ts, src/apps/locked-celo/positions.ts, src/apps/mento/positions.ts, src/apps/moola/positions.ts, src/apps/ubeswap/positions.ts, src/apps/uniswap/positions.ts, src/runtime/getPositions.ts, src/types/positions.ts
First step to be able to able to list possible positions for an app without needing a user address.
The idea is we'll tag some positions for the "earn" feature and the wallet will query for them.
One thing though is for some dapps (uniswap, curve), there could be hundreds of pools, which can make getting the data for them quite expensive in terms of number of RPC calls needed (even with multicall).
We can start by listing the most popular ones and also add caching.
This PR doesn't yet do that and simply returns `[]` (empty list of positions) when a user address isn't provided.
We'll add support for each app incrementally.
I have another PR, showing an example of this for Curve.
Also: this should eventually allow us to remove the optional `getAppTokenDefinition`.
If we're able to list all …
=> feat: allow getting positions without a user address

scripts/triggerShortcut.ts, src/api/index.test.ts, src/api/index.ts, src/apps/gooddollar/shortcuts.ts, src/apps/hedgey/shortcuts.e2e.ts, src/apps/hedgey/shortcuts.ts, src/apps/ubeswap/shortcuts.ts, src/types/address.ts, src/types/shortcuts.ts
Up until now shortcuts were limited to the following input arguments:
- `networkId`
- `address`
- `positionAddress`
This PR allows arbitrary inputs when triggering shortcuts.
`networkId` and `address` are still always required, but any other argument is now up to the shortcut author.
`positionAddress` is now also entirely author defined.
This allows triggering shortcuts with a token and token amount for instance for the "earn" feature of Valora.
And allows for much richer interactions with apps.
Fixes RET-1086
=> feat(shortcuts): author defined trigger inputs

src/apps/ubeswap/positions.e2e.ts
I mocked a bunch of stuff in a previous PR instead of using the runtime for Ubeswap e2e tests. Switching to use the runtime to make the test much more readable.
=> fix(tests): Improve Ubeswap e2e tests

src/apps/compound/positions.ts
Now that we can specify `extraId`, use it instead of the address hack.
=> fix(compound): use extra id

scripts/getPositions.ts, src/api/index.test.ts, src/api/index.ts, src/apps/beefy/positions.e2e.ts, src/apps/compound/positions.e2e.ts, src/apps/ubeswap/positions.e2e.ts, src/config/index.test.ts, src/config/index.ts, src/runtime/client.ts, src/runtime/getPositions.e2e.ts, src/runtime/getPositions.test.ts, src/runtime/getPositions.ts
1. Config moved outside of the API folder
2. Simplification of `getPositions` function
3. Consistency in config values
4. Improved developer experience
The config is now more universally accessible and not limited to the API. The `getClient` function, located outside of the API folder, was already accessing it from the runtime.
Removed the need to pass `GET_TOKEN_INFO_URL` to `getPositions`, simplifying its usage.
There was a mismatch with the `getPositions` script, which was passing a default value for `GET_TOKEN_INFO_URL` that differed from the defaults set in `production.yaml` and `staging.yaml`. This caused the $ price to be unavailable during development. Now, all components read the same config, ensuring consistency and proper defaults for development.
With these updates, running …
=> refactor: unified config access and simplifications for better devx

src/apps/aave/positions.ts, src/apps/aave/shortcuts.ts, src/apps/beefy/api.ts, src/apps/beefy/positions.ts, src/apps/curve/positions.ts, src/apps/stake-dao/positions.ts, src/apps/uniswap/positions.ts, src/runtime/client.ts, src/runtime/isNative.ts, src/types/networkId.ts
This is a quick change to unblock all requests failing since the wallet is now doing requests with `base` as `networkId`.
I'll update the test account to have a few positions too on these networks and will update the e2e tests separately.
=> feat: support polygon, base and their testnet

src/apps/aave/getAaveTokensWithIncentives.ts, src/apps/aave/positions.ts, src/apps/aave/shortcuts.ts
This fixes the incorrect display of rewards for Aave.
The `userRewardsInformation` returned for each a/v/sToken from `getUserReservesIncentivesData`
with `userUnclaimedRewards` can't be used as is and requires some additional calculations to get the total rewards for the user.
In particular if there are multiple Aave assets with incentives yielding a given reward token, the `userUnclaimedRewards` value will be the same across those assets.
And it doesn't include the accrued rewards for the assets currently being held.
The details of these calculations to get the total rewards can be seen in https://github.com/aave/aave-utilities/blob/446d9af6f14154771c0343538b59e2aeb7b38e47/packages/math-utils/src/formatters/incentive/calculate-all-user-incentives.ts#L31
For simplicity we can call …
=> fix(aave): incorrect rewards

src/apps/beefy/api.ts, src/apps/beefy/positions.ts
This also adds fallbackPriceUsd for CLM positions.
So Beefy CLM positions don't miss part of the value.
| Before | After |
|-|-|
| ![IMG_7091](https://github.com/user-attachments/assets/dc0e0b1c-9cd6-4897-aea7-b359c981ca7d) | ![IMG_7092](https://github.com/user-attachments/assets/561af152-57dd-4ddc-8c2e-4c018db26e20) |
Before the change, because we don't have a $ price for MIGGLES, the MIGGLES-WETH position $ value was only showing the WETH part.
=> fix(beefy): add fallbackPriceUsd to CLM positions

src/utils/got.ts
The 5s is a bit arbitrary but from the logs, most requests take a max of 2-3 seconds, so adding this to capture the really slow ones and reduce noise in the logs. Also use debug child logger
=> chore(got): only log response timings if its greater than 5s

package.json
The default concurrency for gen2 Cloud Functions is 1.
Which caused us to hit the max instances limit of 100 when we got more traffic.
I chose 80 as it's the [default recommendation](https://cloud.google.com/run/docs/about-concurrency#maximum_concurrent_requests_per_instance) for Cloud Run. We may need to tweak it.
See Slack [thread](https://valora-app.slack.com/archives/C02N3AR2P2S/p1727207104465159?thread_ts=1727204349.338389&cid=C02N3AR2P2S).
=> ci: set concurrency to 80

src/apps/beefy/positions.ts
An error was being thrown in [here](https://github.com/valora-inc/hooks/blob/main/src/apps/beefy/positions.ts#L55), so I've wrapped the map callback with a try-catch to prevent other pools from not being returned when the error throws.
Part of ACT-1375
=> fix(beefy): try catch on userVaults map callback

src/apps/aave/shortcuts.ts, src/apps/allbridge/shortcuts.ts, src/utils/prepareSwapTransactions.test.ts, src/utils/prepareSwapTransactions.ts
Fails because user wallet doesn't have necessary tokens. No functional change by removing, just saves an API call.
=> chore(earn): Remove SwapDeposit simulateTransaction call that always fails

src/api/index.test.ts, src/api/index.ts
If query param not provided, default to legacy hardcoded list.
Unit tests updated/added.
=> feat(earn): Add supportedPools query param to getEarnPositions

src/apps/beefy/positions.ts, src/apps/compound/positions.ts, src/apps/curve/positions.ts, src/apps/example/positions.ts, src/apps/uniswap/positions.ts, src/types/positions.ts
- Adds an optional `manageUrl` to `displayprops` which can be specified per pool.
- `manageUrl` was added for the following apps:
- Beefy
- Compound
- Curve
- Uniswap
- Example
Part of ACT-1384
=> feat: add manageUrl to displayProps

src/api/index.test.ts, src/apps/aave/positions.ts, src/apps/allbridge/positions.ts, src/apps/beefy/positions.ts, src/apps/example/positions.ts, src/apps/gooddollar/positions.ts, src/apps/halofi/positions.ts, src/apps/hedgey/positions.ts, src/apps/locked-celo/positions.ts, src/apps/mento/positions.ts, src/apps/moola/positions.test.ts, src/apps/moola/positions.ts, src/apps/stake-dao/positions.ts, src/apps/ubeswap/positions.ts, src/runtime/getPositionId.test.ts, src/runtime/getPositions.test.ts, src/types/positions.ts
Aave's ManageUrl was only used in dataProps and this PR adds it to displayProps.
=> style: make manageUrl required

package.json, src/apps/aave/constants.ts, src/apps/aave/positions.ts, yarn.lock
Brings back #610, but removes stable token debt, seems to be all 0x000000... addresses. This should fix the issue related to Aave pool not showing up
=> fix(aave): use latest aave from address book

src/apps/aave/positions.ts, src/apps/allbridge/positions.ts, src/apps/beefy/positions.ts, src/types/positions.ts
`claimType` needed to determine whether to show "Claim Earnings" or "Claim Rewards". `withdrawalIncludesClaim` needed to decide copy for pools that force claim when withdrawing (Allbridge).
=> feat(earn): Add claimType and withdrawalIncludesClaim to dataProps

src/apps/beefy/api.ts, src/apps/beefy/positions.ts, src/types/positions.ts
Code based on: https://github.com/beefyfinance/beefy-v2/blob/main/src/features/data/actions/apy.ts#L46
https://linear.app/valora/issue/ACT-1406/daily-rate
Ran the Beefy UI locally and console.logged the exact totalDaily value from the UI. Verified that it matched the calculation here.
=> feat(earn): Add dailyYieldRatePercentage to beefy dataProps response

src/apps/beefy/positions.test.ts, src/apps/beefy/positions.ts
Unit tests added to cover:
- when there are breakdown components
- when there are no breakdown components
- when it needs to remove `rewardPoolApr`
=> test(beefy): Add unit tests for getDailyYieldRatePercentage

src/apps/aave/shortcuts.ts, src/apps/beefy/shortcuts.ts, src/utils/prepareSwapTransactions.test.ts, src/utils/prepareSwapTransactions.ts
For ACT-1394. 
Changes include:
- Adjusting postHook default estimatedGas for swap-deposit txs
- Using gas from simulation instead of swap provider for swap-deposit txs 
- Swaps use swap provider gas and ignores simulation results here for gas limit of the tx https://github.com/valora-inc/valora-rest-api/blob/ddf710202b63bfd9f02dc104b6aa812d64809c47/src/swaps/simulateSwap.ts#L156, this can be adjusted in swaps but for now trying this out in swap deposit
- Adding 15% buffer to simulation results to be extra cautious
- Replaces the static 250k padding for deposits, but that was actually needed because of an issue with negative gas refunds (fixed in https://github.com/valora-inc/valora-rest-api/pull/1201) 
This can be monitored and adjusted based on these metrics: …
=> feat: adjust estimated gas for deposit shortcuts

src/config/index.ts
Quick follow up from https://github.com/mobilestack-xyz/hooks/pull/649
=> chore: update default GET_TOKENS_INFO_URL during development

src/apps/aave/positions.ts, src/apps/allbridge/positions.ts, src/apps/beefy/positions.test.ts, src/apps/beefy/positions.ts, src/apps/compound/positions.ts, src/apps/curve/positions.ts, src/apps/example/positions.ts, src/apps/gooddollar/positions.ts, src/apps/halofi/positions.ts, src/apps/hedgey/positions.ts, src/apps/locked-celo/positions.ts, src/apps/mento/positions.ts, src/apps/moola/positions.ts, src/apps/stake-dao/positions.ts, src/apps/ubeswap/positions.ts, src/apps/uniswap/positions.ts, src/apps/walletconnect/positions.ts, src/runtime/getPositions.test.ts, src/types/positions.ts
`description` is not used and the `id` is determined from the folder name. So removing to avoid confusion.
Addresses https://github.com/mobilestack-xyz/hooks/pull/692#discussion_r1883666876
=> refactor: remove `id` and `description` from `AppInfo`

src/api/production.yaml
Apps still need to opt-in on a per pool basis via the [statsig earn config](https://console.statsig.com/4plizaPmWwPL21ASV4QAO0/dynamic_configs/earn_config), so this won't afffect anything live right now. It will allow my FaF project to use base pools :)
=> feat: add base to supported earn networks

src/apps/allbridge/api.ts, src/apps/allbridge/positions.ts
Setting an allbridge request header similar to the official SDK in an attempt to get rid of the 403 response
Context: https://valora-app.slack.com/archives/C02N3AR2P2S/p1740482746542719
=> chore: refine allbridge header

src/apps/beefy/positions.ts
Get decimals for the withdraw shortcut from the main token instead of the earned token, since the earned token decimals doesn't match the main token ones.
For instance:
Morpho "Seamless USDC" token -- doesn't match USDC decimals:
https://basescan.org/address/0xf3c4db91f380963e00caa4ac1f0508259c9a3d3a#readContract#F6
Compound USDC token -- doesn't match USDC decimals:
https://basescan.org/address/0xeF6ED674486E54507d0f711C0d388BD8a1552E6F#readContract#F6
However, the balance is stored in main token decimals.
Using earned token decimals leads to inability to withdraw funds using shortcut, throwing the error:
> Fail with error 'ERC20: burn amount exceeds balance' 
([example transaction](https://basescan.org/tx/0x427a181c5f63e41797f34520dc6b60615be406a1dfc8cf63dd1a1472d4338341) trying to …
=> fix(beefy): withdraw shortcut decimals

src/apps/beefy/shortcuts.ts, src/utils/bigInt.ts
Beefy Valut V7 expects the amount of shares, and not the amount of underlying token, to be provided for the `withdraw()` method. This requires us to convert the token amount to a shares amount inside the shortcut to ensure the correct amount is withdrawn.
* [docs](https://docs.beefy.finance/developer-documentation/vault-contract#withdraw)
* [contract code](https://github.com/beefyfinance/beefy-contracts/blob/5b3f00395d70e65f3f246dce30f1219254e8d04d/contracts/BIFI/vaults/BeefyVaultV7.sol#L139-L155)
There is clearly a race condition between reading the contract data and executing the withdrawal, which may affect the precision of the operation. We might want to use a helper contract to encapsulate all readings within a single transaction.
=> fix(beefy): convert token amount to shares amount for withdrawal

src/runtime/getPositions.ts
Cache base tokens info for 5 seconds, while allowing stale-while-revalidate behavior.
This will ensure:
1. Data is always fresh. 5 second lag seems negligible, given the direct request may take 1-3 seconds
2. Data is retrieved fast
=> chore: cache `getTokensInfoWithPrices`
